
project_id = "sxjafhzikftdenqnkcri"

[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.generate-meal-plan-groq]
verify_jwt = false

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.generate-meal-plan]
verify_jwt = false

[functions.generate-rehab-plan]
verify_jwt = false

[functions.generate-meal-plan-llama]
verify_jwt = false
timeout_ms = 120000
import_map_path = "./import_map.json"

[functions.generate-meal-plan-nutri-plus]
verify_jwt = false
timeout_ms = 180000
import_map_path = "./import_map.json"
