
project_id = "sxjafhzikftdenqnkcri"

[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false
timeout_seconds = 60

[functions.generate-meal-plan-groq]
verify_jwt = false
timeout_seconds = 120

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.generate-meal-plan]
verify_jwt = false

[functions.generate-rehab-plan]
verify_jwt = false

[functions.generate-meal-plan-llama]
verify_jwt = false
timeout_seconds = 60
