
project_id = "sxjafhzikftdenqnkcri"

[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.generate-meal-plan-groq]
verify_jwt = false

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.generate-meal-plan]
verify_jwt = false

[functions.generate-rehab-plan]
verify_jwt = false

[functions.generate-meal-plan-llama]
verify_jwt = false
timeoutMs = 120000
importMapPath = "./import_map.json"
