
project_id = "sxjafhzikftdenqnkcri"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.generate-meal-plan]
verify_jwt = true

[import_map]
imports = { xhr = "https://deno.land/x/xhr@0.1.0/mod.ts" }
