
project_id = "sxjafhzikftdenqnkcri"

[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.check-mercadopago-payment]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = false

