
project_id = "sxjafhzikftdenqnkcri"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.create-asaas-payment]
verify_jwt = true

[functions.check-asaas-payment]
verify_jwt = true
