
project_id = "sxjafhzikftdenqnkcri"

# Funções principais - mantendo apenas estas habilitadas e desabilitando o resto
[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.check-mercadopago-payment]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = false

# Todas as outras funções estão desabilitadas para permanecer dentro dos limites de funções do Supabase
