
project_id = "sxjafhzikftdenqnkcri"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.create-asaas-payment]
verify_jwt = true

[functions.check-asaas-payment]
verify_jwt = true

[functions.create-mercadopago-preference]
verify_jwt = true

[functions.check-mercadopago-payment]
verify_jwt = true

[functions.handle-mercadopago-webhook]
verify_jwt = false

[functions.generate-rehab-plan]
verify_jwt = true

[functions.generate-meal-plan]
verify_jwt = true

[functions.generate-workout-plan]
verify_jwt = true

[functions.grant-plan-access]
verify_jwt = true

[functions.llama-chat]
verify_jwt = true

[functions.llama-agent]
verify_jwt = true
