
project_id = "sxjafhzikftdenqnkcri"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.create-asaas-payment]
verify_jwt = true

[functions.check-asaas-payment]
verify_jwt = true

[functions.create-mercadopago-preference]
verify_jwt = true

[functions.check-mercadopago-payment]
verify_jwt = true

[functions.handle-mercadopago-webhook]
verify_jwt = false

[functions.generate-rehab-plan]
verify_jwt = true

[functions.generate-workout-plan]
verify_jwt = true

[functions.generate-meal-plan]
verify_jwt = true

[functions.generate-meal-plan-groq]
verify_jwt = false

[functions.grant-plan-access]
verify_jwt = true

[functions.mental-health-chat]
verify_jwt = true

[functions.llama-completion]
verify_jwt = true

[functions.groq-chat]
verify_jwt = true

[functions.llama-edge]
verify_jwt = false
timeout_ms = 120000

[functions.generate-meal-plan-llama]
verify_jwt = false
timeout_ms = 120000

[functions.generate-meal-plan-nutri-plus]
verify_jwt = false
timeout_ms = 180000
