project_id = "sxjafhzikftdenqnkcri"

# Critical functions only - keep only essential services
[functions.generate-workout-plan]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = false

[functions.check-mercadopago-payment]
verify_jwt = false

# All other functions are disabled to stay within the plan limits
