
project_id = "sxjafhzikftdenqnkcri"

[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.generate-meal-plan-groq]
verify_jwt = false

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.generate-rehab-plan]
verify_jwt = false

[functions.analyze-assessment-results]
verify_jwt = false

[functions.generate-meal-suggestions]
verify_jwt = false
