
project_id = "sxjafhzikftdenqnkcri"

# Funções principais - mantendo apenas estas habilitadas e desabilitando o resto
[functions.mental-health-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.generate-rehab-plan-groq]
verify_jwt = false

[functions.check-mercadopago-payment]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = false

[functions.generate-workout-plan]
verify_jwt = false

[functions.generate-workout-plan-llama]
verify_jwt = false

# Disable all other functions to stay within the limits
# We prioritized functions that are actively being used in the application
