
project_id = "sxjafhzikftdenqnkcri"

# Keep only the absolute minimum functions needed
# All others will be disabled to stay within the plan limits
[functions]

[functions.generate-workout-plan]
verify_jwt = false

[functions.check-auth-status]
verify_jwt = false
