
project_id = "sxjafhzikftdenqnkcri"
# Increase the timeout for this function to allow the LLM more processing time
timeout_seconds = 300
# Set compute to "optimized" for faster processing
compute = "compute-optimized"
import_map = "../import_map.json"
